### PR TITLE
Snake speed options

### PR DESCRIPTION
**Pull request by alexsrk09**

### CODE REVIEW

**Comment by ZacharyPatten** [comment]
@alexsrk09 Thanks for the interest in contributing! :) Sorry it took me a while to respond.

My initial review notes:
1. `int.TryParse` is better than `Convert.ToInt32` with exception handling
2. I want to keep all the output in English
3. This change would also need to be applied to the web version of the game located here: https://github.com/dotnet/dotnet-console-games/blob/main/Projects/Website/Games/Snake/Snake.cs

Please reply to https://github.com/dotnet/dotnet-console-games/pull/87#issuecomment-1749138553. After you do so, I can help with each of those topics.

**Comment by alexsrk09** [comment]
> @alexsrk09 Thanks for the interest in contributing! :) Sorry it took me a while to respond.
> 
> My initial review notes:
> 
> 1. `int.TryParse` is better than `Convert.ToInt32` with exception handling
> 2. I want to keep all the output in English
> 3. This change would also need to be applied to the web version of the game located here: https://github.com/dotnet/dotnet-console-games/blob/main/Projects/Website/Games/Snake/Snake.cs
> 
> Please reply to [#87 (comment)](https://github.com/dotnet/dotnet-console-games/pull/87#issuecomment-1749138553). After you do so, I can help with each of these topics.

@ZacharyPatten thank you very much for your reply!
This is my first contribution, our programming teacher has recommended this repo to us to learn c#, anyway, I have no problem correcting those 3 points that you have pointed out to me!

**Comment by alexsrk09** [comment]
> @dotnet-policy-service agree

**Comment by alexsrk09** [comment]
> @alexsrk09 Thanks for the interest in contributing! :) Sorry it took me a while to respond.
> 
> My initial review notes:
> 
> 1. `int.TryParse` is better than `Convert.ToInt32` with exception handling
> 2. I want to keep all the output in English
> 3. This change would also need to be applied to the web version of the game located here: https://github.com/dotnet/dotnet-console-games/blob/main/Projects/Website/Games/Snake/Snake.cs
> 
> Please reply to [#87 (comment)](https://github.com/dotnet/dotnet-console-games/pull/87#issuecomment-1749138553). After you do so, I can help with each of these topics.
all 3 topics done!

**Comment by ZacharyPatten** [comment]
@alexsrk09 Thanks for contributing! :tada:

**Pull request merged**
