### PR TITLE
`Oligopoly` update

### PR DESCRIPTION
**Pull request by Fuinny**
Hello! I made some updates to Oligopoly:

* I changed the design of letters and tables a little.
* I added a turn counter.
* I added the `UpdateSharePrices` method, which changes the prices of all companies in the range from -3 to 3 percent. I thought it would make the gaming market a little more dynamic. 
* I added two new companies and events to them (adding new companies and events would probably be a good first issue btw :D)
* I added global events, they are generated every 50th turn and affect the prices of all companies.
* I added the ability to choose difficulty and game mode.

### CODE REVIEW

**Comment by ZacharyPatten** [comment]
Thanks for another pull request.

Feel free to try it if you want to, but I can update the web version of the code for you to match your latest console version.

I'll review this pull request as soon as I can.

**Comment by Fuinny** [comment]
Okay, at least I tried :D

**Comment by Fuinny** [comment]
I think I fixed it... feel dumb :D

**Comment by ZacharyPatten** [comment]
Okay I had some time to review the pull request and here are some comments I have:

I don't think there should be multiple screens for choosing game-mode/difficulty. Right now the code has both a "GAME MODE" screen and a "DIFFICULTY" screen. Instead just have a single options screen maybe with a check box for having "random starting stock values" as a toggle-able option.

I like the idea of adding different difficulties, but changing the `LosingNetWorth` and `WinningNetWorth` isn't actually changing the statistical difficulty of the game. All this does is change how long the game is to play in order to win or lose. Instead, if we want to add different difficulties into the game, we should apply a weight to the random selection of events to so there is a bias towards positive/negative events based on the current difficulty. I don't think we need to change the `LosingNetWorth` and `WinningNetWorth` between the difficulties personally, just the event bias.

**Comment by ZacharyPatten** [comment]
@Fuinny

If you would like me to make the changes to difficulty that I am recommending let me know. But since that would be a change to the game's design I wanted to wait and hear your thoughts before I made that change.

**Comment by Fuinny** [comment]
@ZacharyPatten 

Thanks for reviewing my code! 

Yes, I think that changing the chances of events would be more interesting than changing the win/lose conditions. I did not even think about such an implementation of difficulties, thanks for the improved idea! 

Also, as a suggestion, we can add another checkbox (along with the random mode) that will allow the player to manually adjust the amount of money at the start. It can be called something like _custom mode_ or something (and we also need to prevent the player from selecting both modes at the same time). What do you think?

**Comment by ZacharyPatten** [comment]
> @ZacharyPatten
> 
> Thanks for reviewing my code!
> 
> Yes, I think that changing the chances of events would be more interesting than changing the win/lose conditions. I did not even think about such an implementation of difficulties, thanks for the improved idea!
> 
> Also, as a suggestion, we can add another checkbox (along with the random mode) that will allow the player to manually adjust the amount of money at the start. It can be called something like _custom mode_ or something (and we also need to prevent the player from selecting both modes at the same time). What do you think?

Yeah having a slider or whatever for initial funds is probably a good idea. :) Would you like me to jump in and implement these changes your would you like to work on them? I just don't want us to step on each other's toes by both working on those changes at the same time.

**Comment by Fuinny** [comment]
To be honest, I need help with the implementation of this :D I don't really know how implement these changes, much less how to implement them so that they fit well into the current code. Thanks in advance for your help and time!

**Comment by ZacharyPatten** [comment]
Okay. I'll work on these changes when I have time. :)

**Comment by Fuinny** [comment]
@dotnet-policy-service agree

**Pull request closed without merging**
